name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
    - run: npm run build
    - run: npm run publish-mfe -- --supabaseAuth ${{ secrets.SUPABASE_AUTH }}
